#ifndef PARAMETER_H
#define PARAMETER_H

#define CNN_KERNEL_SIZE      (3)
#define MAX_POOL_KERNEL_SIZE (2)

#define INPUT_IMG_WIDTH      (28)
#define INPUT_IMG_HEIGHT     (28)
#define INPUT_IMG_SIZE       (INPUT_IMG_WIDTH * INPUT_IMG_HEIGHT)

#define FILTERED_IMG_WIDTH0  (INPUT_IMG_WIDTH  - CNN_KERNEL_SIZE + 1)
#define FILTERED_IMG_HEIGHT0 (INPUT_IMG_HEIGHT - CNN_KERNEL_SIZE + 1)
#define CONV_IMG_WIDTH0      (FILTERED_IMG_WIDTH0  / MAX_POOL_KERNEL_SIZE)
#define CONV_IMG_HEIGHT0     (FILTERED_IMG_HEIGHT0 / MAX_POOL_KERNEL_SIZE)

#define FILTERED_IMG_WIDTH1  (CONV_IMG_WIDTH0  - CNN_KERNEL_SIZE + 1)
#define FILTERED_IMG_HEIGHT1 (CONV_IMG_HEIGHT0 - CNN_KERNEL_SIZE + 1)
#define CONV_IMG_WIDTH1      (FILTERED_IMG_WIDTH1  / MAX_POOL_KERNEL_SIZE)
#define CONV_IMG_HEIGHT1     (FILTERED_IMG_HEIGHT1 / MAX_POOL_KERNEL_SIZE)

#endif