#define CNN_KERNEL_SIZE      (3)
#define MAX_POOL_KERNEL_SIZE (2)

#define INPUT_IMG_WIDTH      (28)
#define INPUT_IMG_HEIGHT     (28)
#define INPUT_IMG_SIZE       (INPUT_IMG_WIDTH * INPUT_IMG_HEIGHT)

#define CONV0_IMG_WIDTH      (INPUT_IMG_WIDTH  - CNN_KERNEL_SIZE + 1)
#define CONV0_IMG_HEIGHT     (INPUT_IMG_HEIGHT - CNN_KERNEL_SIZE + 1)
#define MAX_POOL0_IMG_WIDTH  (CONV0_IMG_WIDTH  - MAX_POOL_KERNEL_SIZE + 1)
#define MAX_POOL0_IMG_HEIGHT (CONV0_IMG_HEIGHT - MAX_POOL_KERNEL_SIZE + 1)